site_name: x16-docs
site_description: Commander X16 Documentation (CC BY-SA)
site_author: The Network Entropologist
theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            separate_signature: true
            heading_level: 2
            merge_init_into_class: true



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji